# Generated by Django 5.0.6 on 2024-06-06 02:44

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("execute_date", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (tasks.models.Category["STUDY"], "study"),
                            (tasks.models.Category["WORK"], "work"),
                            (tasks.models.Category["HOME"], "home"),
                            (tasks.models.Category["LEISURE"], "leisure"),
                            (tasks.models.Category["FOOD"], "food"),
                        ],
                        max_length=30,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
