# Generated by Django 5.0.6 on 2024-06-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="execute_date",
            field=models.DateField(),
        ),
    ]
