# Generated by Django 5.0.6 on 2024-06-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("home", "home"),
                    ("leisure", "leisure"),
                    ("food", "food"),
                    ("personal", "personal"),
                    ("work", "work"),
                    ("study", "study"),
                ],
                max_length=30,
            ),
        ),
    ]
